#!/bin/bash
# Install latest Miniconda3 on your machine
# Usage: source ./install-conda

rm -rf ~/.local/share/conda
[[ "$(uname -s)" == "Darwin" ]] && os="MacOSX" || os="Linux"
wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-$os-x86_64.sh" -O ~/miniconda.sh
chmod +x ~/miniconda.sh
~/miniconda.sh -b -p  ~/.local/share/conda
rm -rf ~/miniconda.sh
