#!/bin/bash
# Format LaTeX file, then convert it to PDF, and clean up auxiliary files.

# format
~/.local/bin/latexindent/latexindent.pl $1 > ./.tmp.tex
rm -rf $1
mv ./.tmp.tex $1
rm -rf ./.tmp.tex indent.log

# convert to PDF
pdflatex $1

# clean up auxiliary files
trash ${1%.*}.{aux,fdb_latexmk,fls,log,out,synctex.gz}

