#!/bin/bash
# Format LaTeX file, then convert it to PDF, and clean up auxiliary files.

# format
tempfile="./.tmp.tex"
if [[ "$(uname -s)" == "Darwin" ]]; then
    /usr/local/Cellar/latexindent/3.11/bin/latexindent $1 > $tempfile
else
    ~/.local/bin/latexindent/latexindent.pl $1 > $tempfile
fi

rm -rf $1
mv $tempfile $1
rm -rf $tempfile indent.log

# convert to PDF
pdflatex $1

# clean up auxiliary files
trash ${1%.*}.{aux,log,out}

