#!/bin/bash
# Display the Linux PATH variable with entries separated by \n. 
# The usual "echo $PATH" is messy.
# Usage: ./path

if [[ "$SHELL" == "/bin/zsh" ]]; then
    source ~/.zshrc
else
    source ~/.bashrc
fi
tr ':' '\n' <<< \"$PATH\" | less
