#!/bin/bash

# Install coc.nvim extensions
extpath=~/.config/coc/extensions
mkdir -p "$extpath"
cd "$extpath" || return
if [ ! -f package.json ]
then
  echo '{"dependencies":{}}'> package.json
fi

npm install \
      coc-spell-checker \
      coc-snippets \
      coc-explorer \
      coc-vimlsp \
      coc-highlight \
      coc-pyright \
      coc-go \
      coc-java \
      coc-html \
      coc-css \
      coc-tsserver \
      coc-json \
      coc-sql \
      coc-clangd \
	--global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
