#!/bin/bash
<<DETAILS
Set up a new system with my preferred packages.
Usage: ./system-setup
DETAILS

echo -e "Starting system setup...\n"

# Install pip3 for default python3 on Linux
sudo apt install python3-pip

# Intall bash-wakatime
pip3 install wakatime
git clone https://github.com/gjsheep/bash-wakatime.git ~/.local/share/bash-wakatime

##########
# Vim
##########

sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt-get update

# Update vim version
sudo apt install vim

# Vim plugins: install dependencies
## 1. YouCompleteMe
if [ -f ~/.vim/bundle/YouCompleteMe/install.py ]; then
    sudo apt install build-essential cmake
    python3 ~/.vim/bundle/YouCompleteMe/install.py --all
fi
## 2. vim-autoformat (default format programs) 
sudo apt-get install python-autopep8 # Python
sudo npm install -g remark-cli # Markdown
sudo npm install -g fixjson # JSON
sudo npm install -g js-beautify # HTML, CSS, JS 

# linter used by ale (vim) for bash/sh; can also be used in terminal
sudo apt install shellcheck

# Silver Searcher
sudo apt-get install silversearcher-ag

##############
# Programming
##############

# Java (default v11)
sudo apt install default-jdk

# LaTeX (uncomment if necessary)
# sudo apt-get install texlive texlive-pictures texlive-latex-extra texlive-xetex
# sudo apt install chktex # linter used by ale for vim

###############
# Misc./System
###############

# ZSH
sudo apt install zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# trash-cli (safer alternative to rm -rf)
sudo apt install trash-cli

# tdlr; (man, but with examples)
sudo apt install tldr && tldr

# https://github.com/chubin/cheat.sh
curl https://cht.sh/:cht.sh > ~/.local/bin/cht.sh
chmod +x ~/.local/bin/cht.sh

# zip (in case tar.gz won't do)
sudo apt install zip

# bat (a cat clone, with syntax highlighting)
wget https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
sudo dpkg -i bat_0.15.4_amd64.deb
rm -rf bat_0.15.4_amd64.deb


echo -e "\nSystem setup complete!\n"
