#!/bin/bash
<<DETAILS
Set up a new system with my preferred packages.
Usage: ./system-setup
DETAILS

echo -e "Starting system setup...\n"

##############
# Programming
##############

# Install pip3 for default python3 on Linux
sudo apt install python3-pip

# Intall bash-wakatime
pip3 install wakatime
git clone https://github.com/gjsheep/bash-wakatime.git $HOME/.local/share/bash-wakatime

# set up for ZSH wakatime
git clone https://github.com/sobolevn/wakatime-zsh-plugin.git $HOME/.zsh/custom/plugins/wakatime


read -p "Enter WakaTime API Key: " key
echo -e """
[settings]
debug = false
hidefilenames = false
ignore =
    COMMIT_EDITMSG$
    PULLREQ_EDITMSG$
    MERGE_MSG$
    TAG_EDITMSG$
api_key=$key
""" > $HOME/.wakatime.cfg

# Java (default v11)
sudo apt install default-jdk

# LaTeX (uncomment if necessary)
# sudo apt-get install texlive texlive-pictures texlive-latex-extra texlive-xetex
# sudo apt install chktex # linter used by ale for vim


##########
# Vim
##########

sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt-get update

# Update vim version
sudo apt install vim

## vim-autoformat (default format programs) 
sudo apt-get install python-autopep8 # Python
sudo npm install -g remark-cli # Markdown
sudo npm install -g fixjson # JSON
sudo npm install -g js-beautify # HTML, CSS, JS 

# linter used by ale (vim) for bash/sh; can also be used in terminal
sudo apt install shellcheck

# Silver Searcher
sudo apt-get install silversearcher-ag


###############
# Misc./System
###############

# TODO: Install fzf for oh my zsh plugin?

# ZSH
sudo apt install zsh
# oh my zsh will start a sub-shell, just "exit" and the this setup script will continue
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
mv $HOME/.zshrc.pre-oh-my-zsh $HOME/.zshrc
sudo apt install command-not-found

# trash-cli (safer alternative to rm -rf)
sudo apt install trash-cli

# tdlr; (man, but with examples)
sudo apt install tldr && tldr

# https://github.com/chubin/cheat.sh
curl https://cht.sh/:cht.sh > $HOME/.local/bin/cht.sh
chmod +x $HOME/.local/bin/cht.sh

# zip (in case tar.gz won't do)
sudo apt install zip

# bat (a cat clone, with syntax highlighting)
wget https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
sudo dpkg -i bat_0.15.4_amd64.deb
rm -rf bat_0.15.4_amd64.deb


echo -e "\nSystem setup complete!\n"
